version: '2.1'

services:
  meugastosapi:
    image: meugastosapi
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3003:3003
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 src/loader.js